#%RAML 1.0
title: Test API
version: v3
baseUri: https://api.github.com
annotationTypes:
  exitCode: integer
  commandPattern: string
/echo1/{message}:
  uriParameters:
    message:
      type: string
      required: true
  get:
    (commandPattern): echo {{.message}}
    responses:
      200:
        (exitCode): 0
        body:
          text/plain:
            type: string
